# Exercises Lab06 Growing Containers

`1.` Here are some beverages:  "Water", "Tea", "Coffee".  And here are some more: "Milk", "Kefir", "Lemonade".

> a. Make two lists of 3 beverages each.

In [35]:
some = ["Water", "Tea", "Coffee"]
more = ["Milk", "Kefir", "Lemonade"]

> b. Put your two lists into one big list in three different ways.

In [36]:
all_drinks = some + more
all_drinks

['Water', 'Tea', 'Coffee', 'Milk', 'Kefir', 'Lemonade']

In [37]:
some += more
some

['Water', 'Tea', 'Coffee', 'Milk', 'Kefir', 'Lemonade']

In [38]:
some = ["Water", "Tea", "Coffee"]
some.extend(more)
some

['Water', 'Tea', 'Coffee', 'Milk', 'Kefir', 'Lemonade']

> c. Add "Beer" to your big list in 3 different ways.

In [39]:
all_drinks += "Beer"
all_drinks

['Water', 'Tea', 'Coffee', 'Milk', 'Kefir', 'Lemonade', 'B', 'e', 'e', 'r']

In [40]:
all_drinks = ['Water', 'Tea', 'Coffee', 'Milk', 'Kefir', 'Lemonade']
all_drinks += ["Beer"]
all_drinks

['Water', 'Tea', 'Coffee', 'Milk', 'Kefir', 'Lemonade', 'Beer']

In [41]:
all_drinks.extend(["Beer"])
all_drinks

['Water', 'Tea', 'Coffee', 'Milk', 'Kefir', 'Lemonade', 'Beer', 'Beer']

In [42]:
all_drinks.append("Beer")
all_drinks

['Water', 'Tea', 'Coffee', 'Milk', 'Kefir', 'Lemonade', 'Beer', 'Beer', 'Beer']

In [43]:
all_drinks += "Beer",
", ".join(all_drinks)

'Water, Tea, Coffee, Milk, Kefir, Lemonade, Beer, Beer, Beer, Beer'

> d. Get "Beer" into your `list` one more time, this time at the front of the list.

In [44]:
all_drinks.insert(0, "Beer")
", ".join(all_drinks)

'Beer, Water, Tea, Coffee, Milk, Kefir, Lemonade, Beer, Beer, Beer, Beer'

`2.`  Matching.  Some on the left have more than one answer on the right, and vice versa:

|with this data type|you use this|facility to grow or sort|
    |-------------:|:---:|:----|
    |list| |1. sort_values|
    |    |  |2. sorted|
    |np.array |  |3. += |
    |          |  |4. sort|
    |pd.Series |  |5. append|
    |          |   |6. extend|
    |pd.DataFrame|  |7. concatenate|
    |    |    | 8. join |

.

|with this data type|you use this|facility to grow or sort
    |-------------:|:---:|:----|
    |list|2, 3, 4, 5, 6  |1. sort_values|
    |    |  |2. sorted|
    |np.array | 4, 5, 7  |3. += |
    |          |  |4. sort|
    |pd.Series | 1, 5, 8  |5. append|
    |          |   |6. extend|
    |pd.DataFrame|1, 5, 6, 8|7. concatenate|
    |         |      |   8. join |

`3.` Numpy has its own `random` sub-module.  Discover what's in it using `np.random.->` or `dir(np.random)`.  

>  a. Practice by making a 3 x 4 matrix of normally distributed random numbers.  

In [45]:
?np.random.randn

In [46]:
import numpy as np
normals = np.random.randn(3, 4)
normals

array([[ 0.15190329,  0.23479152,  0.40552453,  1.12441686],
       [ 2.32233667, -0.2518111 , -0.42067076, -0.2365433 ],
       [ 0.9257997 ,  1.32283873, -0.72093459,  1.1005005 ]])

>  b. Study the result of `?np.random.random` and/or `?np.random.random_sample`.  They are the same.  Make a 3 x 5 matrix of random numbers, uniformly distributed between 1 and 100.

In [47]:
randoms = 99 * np.random.random((3, 5)) + 1
randoms

array([[ 31.8691602 ,   3.21094295,  73.88697342,  14.60579637,
         41.39146144],
       [  7.93611511,  13.35649519,  92.35715302,  94.93968844,
         25.87341032],
       [ 11.34721174,  53.96518636,   7.18197063,  33.56500911,
         56.82253968]])

>  c. Paste your two matrices together so you have a 3 X 9 matrix using append.

In [48]:
appended = np.append(normals, randoms, axis=1)
appended

array([[  0.15190329,   0.23479152,   0.40552453,   1.12441686,
         31.8691602 ,   3.21094295,  73.88697342,  14.60579637,
         41.39146144],
       [  2.32233667,  -0.2518111 ,  -0.42067076,  -0.2365433 ,
          7.93611511,  13.35649519,  92.35715302,  94.93968844,
         25.87341032],
       [  0.9257997 ,   1.32283873,  -0.72093459,   1.1005005 ,
         11.34721174,  53.96518636,   7.18197063,  33.56500911,
         56.82253968]])

>  d. Study the help for `np.concatenate`.  Use `concatenate` to get the same result.

In [49]:
concatenated = np.concatenate((normals, randoms), axis=1)
concatenated

array([[  0.15190329,   0.23479152,   0.40552453,   1.12441686,
         31.8691602 ,   3.21094295,  73.88697342,  14.60579637,
         41.39146144],
       [  2.32233667,  -0.2518111 ,  -0.42067076,  -0.2365433 ,
          7.93611511,  13.35649519,  92.35715302,  94.93968844,
         25.87341032],
       [  0.9257997 ,   1.32283873,  -0.72093459,   1.1005005 ,
         11.34721174,  53.96518636,   7.18197063,  33.56500911,
         56.82253968]])

>  e. Check your results by using `c_result.shape` and `d_result.shape`.  Also, check `c_result == d_result`.

In [50]:
appended.shape, concatenated.shape, appended == concatenated

((3, 9),
 (3, 9),
 array([[ True,  True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True]], dtype=bool))

`4`.  Put these data in a DataFrame:

```python
data = [["one", "two"],
        [1    , 2    ]]
```

In [51]:
import pandas as pd
df = pd.DataFrame([['one', 'two'], [1, 2]])
df

0    1
0  one  two
1    1    2

> `a`.  Add a `"three", 3` column.

In [52]:
df[2] = ["three", 3]
df

0    1      2
0  one  two  three
1    1    2      3

> `b`.  Add a row of the Spanish words:  uno, dos, tres; or use your own language.


In [53]:
df = df.append([["uno","dos","tres"]])
df

0    1      2
0  one  two  three
1    1    2      3
0  uno  dos   tres

> `c`. Rename the index to be "English", "Number", "Spanish"  and the columns to be 1, 2, 3.

In [54]:
df.columns = [1, 2, 3]
df.index = ["English", "Number", "Spanish"]
df

1    2      3
English  one  two  three
Number     1    2      3
Spanish  uno  dos   tres

> `d.`  With `df.reindex(new_index)` you can move the index to a different order and each row will follow its index.
>       Use `df.reindex` to make the order be ["Number", "English", "Spanish"].

In [55]:
df.reindex(["Number", "English", "Spanish"])

1    2      3
Number     1    2      3
English  one  two  three
Spanish  uno  dos   tres

In [56]:
# 5 a. Here are some data representing some state's population.  Get them into a data frame.

index= ['California', 'Florida', 'Pennsylvania', 'Ohio', 'North Carolina', 'New Jersey', 'Washington', 'Massachusetts', 'Indiana', 'Maryland', 'Colorado', 'South Carolina', 'Louisiana', 'Oregon', 'Connecticut', 'Utah', 'Nevada', 'Kansas', 'Nebraska', 'Idaho', 'New Hampshire', 'Rhode Island', 'Delaware', 'North Dakota', 'Vermont']
columns= ['Pop 2017', 'Rank 2017', 'Pop/Seat, 2017']
values = [['39,536,653', 1, '718,848'],
['20,984,400', 3, '734,904'],
['12,805,537', 5, '640,277'],
['11,658,609', 7, '647,701'],
['10,273,419', 9, '684,895'],
['9,005,644', 11, '643,260'],
['7,405,743', 13, '617,145'],
['6,859,819', 15, '623,620'],
['6,666,818', 17, '606,074'],
['6,052,177', 19, '605,218'],
['5,607,154', 21, '623,017'],
['5,024,369', 23, '558,263'],
['4,684,333', 25, '585,542'],
['4,142,776', 27, '591,825'],
['3,588,184', 29, '512,598'],
['3,101,833', 31, '516,972'],
['2,998,039', 33, '499,673'],
['2,913,123', 35, '485,521'],
['1,920,076', 37, '384,015'],
['1,716,943', 39, '429,236'],
['1,342,795', 41, '335,699'],
['1,059,639', 43, '264,910'],
['961,939', 45, '320,646'],
['755,393', 47, '251,798'],
['623,657', 49, '207,886']]

In [57]:
some_states = pd.DataFrame(values, columns=columns, index=index)
some_states.index.name = 'State'
some_states

Pop 2017  Rank 2017 Pop/Seat, 2017
State                                               
California      39,536,653          1        718,848
Florida         20,984,400          3        734,904
Pennsylvania    12,805,537          5        640,277
Ohio            11,658,609          7        647,701
North Carolina  10,273,419          9        684,895
New Jersey       9,005,644         11        643,260
Washington       7,405,743         13        617,145
Massachusetts    6,859,819         15        623,620
Indiana          6,666,818         17        606,074
Maryland         6,052,177         19        605,218
Colorado         5,607,154         21        623,017
South Carolina   5,024,369         23        558,263
Louisiana        4,684,333         25        585,542
Oregon           4,142,776         27        591,825
Connecticut      3,588,184         29        512,598
Utah             3,101,833         31        516,972
Nevada           2,998,039         33        499,673
Kansas           2,913,123         35        485,521
Nebraska         1,920,076         37        384,015
Idaho            1,716,943         39        429,236
New Hampshire    1,342,795         41        335,699
Rhode Island     1,059,639         43        264,910
Delaware           961,939         45        320,646
North Dakota       755,393         47        251,798
Vermont            623,657         49        207,886

In [58]:
# 5.b And here are some more states and their populations. Get them into a dataframe.

data = [['State', 'Pop 2017', 'Rank 2017', 'Pop/Seat, 2017'],
['Texas', '28,304,596', 2, '744,858'],
['New York', '19,849,399', 4, '684,462'],
['Illinois', '12,802,023', 6, '640,101'],
['Georgia', '10,429,379', 8, '651,836'],
['Michigan', '9,962,311', 10, '622,644'],
['Virginia', '8,470,020', 12, '651,540'],
['Arizona', '7,016,270', 14, '637,843'],
['Tennessee', '6,715,984', 16, '610,544'],
['Missouri', '6,113,532', 18, '611,353'],
['Wisconsin', '5,795,483', 20, '579,548'],
['Minnesota', '5,576,606', 22, '557,661'],
['Alabama', '4,874,747', 24, '541,639'],
['Kentucky', '4,454,189', 26, '556,774'],
['Oklahoma', '3,930,864', 28, '561,552'],
['Iowa', '3,145,711', 30, '524,285'],
['Arkansas', '3,004,279', 32, '500,713'],
['Mississippi', '2,984,100', 34, '497,350'],
['New Mexico', '2,088,070', 36, '417,614'],
['West Virginia', '1,815,857', 38, '363,171'],
['Hawaii', '1,427,538', 40, '356,885'],
['Maine', '1,335,907', 42, '333,977'],
['Montana', '1,050,493', 44, '350,164'],
['South Dakota', '869,666', 46, '289,889'],
['Alaska', '739,795', 48, '246,598'],
['Wyoming', '579,315', 50, '193,105']]


In [59]:
more_states = pd.DataFrame(data[1:])
more_states.columns = data[0]
more_states = more_states.set_index('State')
more_states

Pop 2017  Rank 2017 Pop/Seat, 2017
State                                              
Texas          28,304,596          2        744,858
New York       19,849,399          4        684,462
Illinois       12,802,023          6        640,101
Georgia        10,429,379          8        651,836
Michigan        9,962,311         10        622,644
Virginia        8,470,020         12        651,540
Arizona         7,016,270         14        637,843
Tennessee       6,715,984         16        610,544
Missouri        6,113,532         18        611,353
Wisconsin       5,795,483         20        579,548
Minnesota       5,576,606         22        557,661
Alabama         4,874,747         24        541,639
Kentucky        4,454,189         26        556,774
Oklahoma        3,930,864         28        561,552
Iowa            3,145,711         30        524,285
Arkansas        3,004,279         32        500,713
Mississippi     2,984,100         34        497,350
New Mexico      2,088,070         36        417,614
West Virginia   1,815,857         38        363,171
Hawaii          1,427,538         40        356,885
Maine           1,335,907         42        333,977
Montana         1,050,493         44        350,164
South Dakota      869,666         46        289,889
Alaska            739,795         48        246,598
Wyoming           579,315         50        193,105

In [60]:
# 5.c.  Finally, here are some data for each state's symbols.  Make them into another dataframe.

index= ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming', 'Washington, D.C.']
columns= ['Capital', 'Largest City', 'Bird', 'Flower']
values = [['Montgomery', 'Birmingham', 'Yellowhammer', 'Camellia'],
['Juneau', 'Anchorage', 'Willow Ptarmigan', 'Forget-me-not'],
['Phoenix', 'Phoenix', 'Cactus Wren', 'Saguaro Cactus Blossom'],
['Little Rock', 'Little Rock', 'Mockingbird', 'Apple Blossom'],
['Sacramento', 'Los Angeles', 'California Valley Quail', 'Golden Poppy'],
['Denver', 'Denver', 'Lark Bunting', 'Columbine'],
['Hartford', 'Bridgeport', 'American Robin', 'Mountain Laurel'],
['Dover', 'Wilmington', 'Blue Hen Chicken', 'Peach Blossom'],
['Tallahassee', 'Jacksonville', 'Mockingbird', 'Orange Blossom'],
['Atlanta', 'Atlanta', 'Brown Thrasher', 'Cherokee Rose'],
['Honolulu', 'Honolulu', 'Nene (Hawaiian Goose)', 'Hibiscus'],
['Boise', 'Boise', 'Mountain Bluebird', 'Syringa'],
['Springfield', 'Chicago', 'Cardinal', 'Native violet'],
['Indianapolis', 'Indianapolis', 'Cardinal', 'Peony'],
['Des Moines', 'Des Moines', 'Eastern Goldfinch', 'Wild Rose'],
['Topeka', 'Wichita', 'Western Meadowlark', 'Native Sunflower'],
['Frankfort', 'Louisville', 'Kentucky Cardinal', 'Goldenrod'],
['Baton Rouge', 'New Orleans', 'Pelican', 'Magnolia'],
['Augusta', 'Portland', 'Chickadee', 'White Pine Cone and Tassel'],
['Annapolis', 'Baltimore', 'Baltimore Oriole', 'Black-Eyed Susan'],
['Boston', 'Boston', 'Chickadee', 'Mayflower'],
['Lansing', 'Detroit', 'Robin', 'Apple Blossom'],
['St. Paul', 'Minneapolis', 'Common Loon', "Pink and White Lady's Slipper"],
['Jackson', 'Jackson', 'Mockingbird', 'Magnolia'],
['Jefferson City', 'Kansas City', 'Bluebird', 'Hawthorn'],
['Helena', 'Billings', 'Western Meadowlark', 'Bitterroot'],
['Lincoln', 'Omaha', 'Western Meadowlark', 'Goldenrod'],
['Carson City', 'Las Vegas', 'Mountain Bluebird', 'Sagebrush'],
['Concord', 'Manchester', 'Purple Finch', 'Purple Lilac'],
['Trenton', 'Newark', 'Eastern Goldfinch', 'Purple Violet'],
['Santa Fe', 'Albuquerque', 'Roadrunner', 'Yucca Flower'],
['Albany', 'New York', 'Bluebird', 'Rose'],
['Raleigh', 'Charlotte', 'Cardinal', 'Dogwood'],
['Bismarck', 'Fargo', 'Western Meadowlark', 'Wild Prairie Rose'],
['Columbus', 'Columbus', 'Cardinal', 'Scarlet Carnation'],
['Oklahoma City', 'Oklahoma City', 'Scissor-Tailed Flycatcher', 'Mistletoe'],
['Salem', 'Portland', 'Western Meadowlark', 'Oregon Grape'],
['Harrisburg', 'Philadelphia', 'Ruffed Grouse', 'Mountain Laurel'],
['Providence', 'Providence', 'Rhode Island Red', 'Violet'],
['Columbia', 'Columbia', 'Carolina Wren', 'Yellow Jessamine'],
['Pierre', 'Sioux Falls', 'Ring-Necked Pheasant', 'American Pasqueflower'],
['Nashville', 'Memphis', 'Mockingbird', 'Iris'],
['Austin', 'Houston', 'Mockingbird', 'Bluebonnet'],
['Salt Lake City', 'Salt Lake City', 'California Gull', 'Sego Lily'],
['Montpelier', 'Burlington', 'Hermit Thrush', 'Red Clover'],
['Richmond', 'Virginia Beach', 'Cardinal', 'Dogwood'],
['Olympia', 'Seattle', 'Willow Goldfinch', 'Western Rhododendron'],
['Charleston', 'Charleston', 'Cardinal', 'Big Rhododendron'],
['Madison', 'Milwaukee', 'Robin', 'Wood Violet'],
['Cheyenne', 'Cheyenne', 'Meadowlark', 'Indian Paintbrush'],
['None', 'Washington', 'Woodthrush', 'American Beauty Rose']]


In [61]:
symbols = pd.DataFrame(values, columns=columns, index=index)
symbols.index.name = "State"
symbols.info()

<class 'pandas.core.frame.DataFrame'>
Index: 51 entries, Alabama to Washington, D.C.
Data columns (total 4 columns):
Capital         51 non-null object
Largest City    51 non-null object
Bird            51 non-null object
Flower          51 non-null object
dtypes: object(4)
memory usage: 2.0+ KB


In [62]:
symbols.head()

Capital Largest City                     Bird  \
State                                                           
Alabama      Montgomery   Birmingham             Yellowhammer   
Alaska           Juneau    Anchorage         Willow Ptarmigan   
Arizona         Phoenix      Phoenix              Cactus Wren   
Arkansas    Little Rock  Little Rock              Mockingbird   
California   Sacramento  Los Angeles  California Valley Quail   

                            Flower  
State                               
Alabama                   Camellia  
Alaska               Forget-me-not  
Arizona     Saguaro Cactus Blossom  
Arkansas             Apple Blossom  
California            Golden Poppy

> `5. d.` Get all that data into one DataFrame, joined on the state.

In [63]:
all_pops = some_states.append(more_states)
all_pops.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, California to Wyoming
Data columns (total 3 columns):
Pop 2017          50 non-null object
Rank 2017         50 non-null int64
Pop/Seat, 2017    50 non-null object
dtypes: int64(1), object(2)
memory usage: 1.6+ KB


In [64]:
all_pops.head()

Pop 2017  Rank 2017 Pop/Seat, 2017
State                                               
California      39,536,653          1        718,848
Florida         20,984,400          3        734,904
Pennsylvania    12,805,537          5        640,277
Ohio            11,658,609          7        647,701
North Carolina  10,273,419          9        684,895

In [65]:
state_info = symbols.join(all_pops)
state_info

Capital    Largest City                       Bird  \
State                                                                         
Alabama               Montgomery      Birmingham               Yellowhammer   
Alaska                    Juneau       Anchorage           Willow Ptarmigan   
Arizona                  Phoenix         Phoenix                Cactus Wren   
Arkansas             Little Rock     Little Rock                Mockingbird   
California            Sacramento     Los Angeles    California Valley Quail   
Colorado                  Denver          Denver               Lark Bunting   
Connecticut             Hartford      Bridgeport             American Robin   
Delaware                   Dover      Wilmington           Blue Hen Chicken   
Florida              Tallahassee    Jacksonville                Mockingbird   
Georgia                  Atlanta         Atlanta             Brown Thrasher   
Hawaii                  Honolulu        Honolulu      Nene (Hawaiian Goose)   
Idaho                      Boise           Boise          Mountain Bluebird   
Illinois             Springfield         Chicago                   Cardinal   
Indiana             Indianapolis    Indianapolis                   Cardinal   
Iowa                  Des Moines      Des Moines          Eastern Goldfinch   
Kansas                    Topeka         Wichita         Western Meadowlark   
Kentucky               Frankfort      Louisville          Kentucky Cardinal   
Louisiana            Baton Rouge     New Orleans                    Pelican   
Maine                    Augusta        Portland                  Chickadee   
Maryland               Annapolis       Baltimore           Baltimore Oriole   
Massachusetts             Boston          Boston                  Chickadee   
Michigan                 Lansing         Detroit                      Robin   
Minnesota               St. Paul     Minneapolis                Common Loon   
Mississippi              Jackson         Jackson                Mockingbird   
Missouri          Jefferson City     Kansas City                   Bluebird   
Montana                   Helena        Billings         Western Meadowlark   
Nebraska                 Lincoln           Omaha         Western Meadowlark   
Nevada               Carson City       Las Vegas          Mountain Bluebird   
New Hampshire            Concord      Manchester               Purple Finch   
New Jersey               Trenton          Newark          Eastern Goldfinch   
New Mexico              Santa Fe     Albuquerque                 Roadrunner   
New York                  Albany        New York                   Bluebird   
North Carolina           Raleigh       Charlotte                   Cardinal   
North Dakota            Bismarck           Fargo         Western Meadowlark   
Ohio                    Columbus        Columbus                   Cardinal   
Oklahoma           Oklahoma City   Oklahoma City  Scissor-Tailed Flycatcher   
Oregon                     Salem        Portland         Western Meadowlark   
Pennsylvania          Harrisburg    Philadelphia              Ruffed Grouse   
Rhode Island          Providence      Providence           Rhode Island Red   
South Carolina          Columbia        Columbia              Carolina Wren   
South Dakota              Pierre     Sioux Falls       Ring-Necked Pheasant   
Tennessee              Nashville         Memphis                Mockingbird   
Texas                     Austin         Houston                Mockingbird   
Utah              Salt Lake City  Salt Lake City            California Gull   
Vermont               Montpelier      Burlington              Hermit Thrush   
Virginia                Richmond  Virginia Beach                   Cardinal   
Washington               Olympia         Seattle           Willow Goldfinch   
West Virginia         Charleston      Charleston                   Cardinal   
Wisconsin                Madison       Milwaukee                      Robin

` 5. e.` Note that Washington DC had no information about population, nor does it have a state capital. NaN (Not A Number) is placed in those fields by default, which is available to you as `np.nan`.  

Optional now because we will have a lab about this:  Check out `?pd.DataFrame.fillna` to see how to change them from NaN to "missing".  The first argument mentioned is `self`, which is an identifier for the DataFrame that is calling the method.  Python fills that in so you can ignore it.

`df.head()` shows you the first 5 rows of the dataframe.
`df.tail()` shows you the last 5 rows of the dataframe.

In [67]:
state_info = state_info.fillna("missing")
state_info.tail()

Capital Largest City              Bird  \
State                                                         
Washington           Olympia      Seattle  Willow Goldfinch   
West Virginia     Charleston   Charleston          Cardinal   
Wisconsin            Madison    Milwaukee             Robin   
Wyoming             Cheyenne     Cheyenne        Meadowlark   
Washington, D.C.        None   Washington        Woodthrush   

                                Flower   Pop 2017 Rank 2017 Pop/Seat, 2017  
State                                                                       
Washington        Western Rhododendron  7,405,743        13        617,145  
West Virginia         Big Rhododendron  1,815,857        38        363,171  
Wisconsin                  Wood Violet  5,795,483        20        579,548  
Wyoming              Indian Paintbrush    579,315        50        193,105  
Washington, D.C.  American Beauty Rose    missing   missing        missing